name: workflow 1
on: push
jobs:
  run-linters:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install node dedpendencies
        run: npm ci

      - name: run linters
        run: npm run lint

      - name: run test
        run: |
          npm run test
          echo "run ends"

      - name: run build
        run: npm run dev
